// A broad list of U.S. colleges and universities for the onboarding school
// autocomplete. Not exhaustive — students can still type a school that isn't
// listed. Covers flagships, major privates, big athletic programs, HBCUs, and
// well-known regionals across all 50 states.
window.SCHOOLS = [
  // Ivy League
  "Harvard University", "Yale University", "Princeton University", "Columbia University",
  "University of Pennsylvania", "Brown University", "Dartmouth College", "Cornell University",
  // Top privates
  "Stanford University", "Massachusetts Institute of Technology", "California Institute of Technology",
  "Duke University", "University of Chicago", "Northwestern University", "Johns Hopkins University",
  "Vanderbilt University", "Rice University", "Washington University in St. Louis", "Emory University",
  "Georgetown University", "University of Notre Dame", "Carnegie Mellon University", "New York University",
  "Boston University", "Boston College", "Tufts University", "Brandeis University", "Wake Forest University",
  "University of Southern California", "Tulane University", "Southern Methodist University",
  "Pepperdine University", "Syracuse University", "Fordham University", "Villanova University",
  "Georgetown University", "George Washington University", "American University", "Howard University",
  "Spelman College", "Morehouse College", "Hampton University", "Florida A&M University",
  "North Carolina A&T State University", "Xavier University of Louisiana",
  // Liberal arts colleges
  "Williams College", "Amherst College", "Swarthmore College", "Pomona College", "Wellesley College",
  "Bowdoin College", "Middlebury College", "Carleton College", "Claremont McKenna College",
  "Davidson College", "Colby College", "Bates College", "Colgate University", "Hamilton College",
  "Vassar College", "Grinnell College", "Oberlin College", "Kenyon College", "Macalester College",
  "Barnard College", "Smith College", "Mount Holyoke College", "Reed College", "Occidental College",
  // Big public flagships (by state)
  "University of Alabama", "Auburn University", "University of Alaska Anchorage",
  "University of Arizona", "Arizona State University", "University of Arkansas",
  "University of California, Berkeley", "University of California, Los Angeles",
  "University of California, San Diego", "University of California, Davis",
  "University of California, Irvine", "University of California, Santa Barbara",
  "University of California, Santa Cruz", "University of California, Riverside",
  "San Diego State University", "San Jose State University", "Cal Poly San Luis Obispo",
  "University of Colorado Boulder", "Colorado State University", "University of Connecticut",
  "University of Delaware", "University of Florida", "Florida State University",
  "University of Central Florida", "University of Miami", "University of South Florida",
  "University of Georgia", "Georgia Institute of Technology", "Georgia State University",
  "University of Hawaii at Manoa", "University of Idaho", "Boise State University",
  "University of Illinois Urbana-Champaign", "University of Illinois Chicago", "DePaul University",
  "Indiana University Bloomington", "Purdue University", "University of Iowa", "Iowa State University",
  "University of Kansas", "Kansas State University", "University of Kentucky", "University of Louisville",
  "Louisiana State University", "University of Maine", "University of Maryland", "Towson University",
  "University of Massachusetts Amherst", "University of Michigan", "Michigan State University",
  "University of Minnesota", "University of Mississippi", "Mississippi State University",
  "University of Missouri", "University of Montana", "University of Nebraska-Lincoln",
  "University of Nevada, Las Vegas", "University of Nevada, Reno", "University of New Hampshire",
  "Rutgers University", "University of New Mexico", "University at Buffalo",
  "Stony Brook University", "Binghamton University", "University of North Carolina at Chapel Hill",
  "North Carolina State University", "University of North Dakota", "Ohio State University",
  "University of Cincinnati", "Miami University", "Kent State University", "University of Oklahoma",
  "Oklahoma State University", "University of Oregon", "Oregon State University",
  "Pennsylvania State University", "University of Pittsburgh", "Temple University",
  "University of Rhode Island", "University of South Carolina", "Clemson University",
  "University of South Dakota", "University of Tennessee", "University of Texas at Austin",
  "Texas A&M University", "University of Texas at Dallas", "Texas Tech University",
  "University of Houston", "Baylor University", "Texas Christian University", "University of Utah",
  "Utah State University", "Brigham Young University", "University of Vermont", "University of Virginia",
  "Virginia Tech", "George Mason University", "James Madison University", "University of Washington",
  "Washington State University", "West Virginia University", "University of Wisconsin-Madison",
  "Marquette University", "University of Wyoming",
  // Other well-known schools
  "Drexel University", "Northeastern University", "Rochester Institute of Technology",
  "University of Rochester", "Case Western Reserve University", "Lehigh University",
  "Rensselaer Polytechnic Institute", "Worcester Polytechnic Institute", "Stevens Institute of Technology",
  "Santa Clara University", "Loyola Marymount University", "Gonzaga University", "Creighton University",
  "Saint Louis University", "Marquette University", "Xavier University", "Butler University",
  "Elon University", "High Point University", "Chapman University", "University of San Diego",
  "University of San Francisco", "University of Denver", "University of Tulsa", "Hofstra University",
  "Pace University", "The New School", "Pratt Institute", "Parsons School of Design",
  "Savannah College of Art and Design", "Berklee College of Music", "Juilliard School",
  "Babson College", "Bentley University", "Bryant University", "Quinnipiac University",
];
